language: node_js
node_js:
 - stable
services: 
 - mongodb
before_script:
 - npm install -g jasmine-node
 - PATH=${PATH/\.\/node_modules\/\.bin//}
 - find . -name node_modules -prune -o -name spec -execdir npm install \;
 - sleep 15
