swagger: "2.0"
info:
  title: ThrustCurve.org API
  description: Programmatic access to ThrustCurve.org motor and simulator file database.
  contact:
    name: John Coker
    url: http://www.thrustcurve.org/api.html
    email: john@jcsw.com
  license:
    name: ISC
    url: https://opensource.org/licenses/ISC
  version: 1.0.0

host: localhost:3000
basePath: /api/v1
tags:
  - name: metadata
    description: Get metadata about all motors in the database.
  - name: search
    description: Find motors by various criteria.
  - name: download
    description: Retrieve simulator file data for specific motors.

paths:
  /metadata.json:
    get:
      tags:
      - metadata
      description: The GET method specifies search criteria as query parameters.
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - name: manufacturer
        in: query
        description: manufacturer name or abbreviation
        type: string
        required: false
      - name: impulseClass
        in: query
        description: letter class of motor
        type: string
        required: false
      - name: diameter
        in: query
        description: motor diameter in mm
        type: number
        required: false
      - name: type
        in: query
        description: motor type
        type: string
        enum:
        - SU
        - reload
        - hybrid
        required: false
      - name: certOrg
        in: query
        description: certification organization name or abbreviation
        type: string
        required: false
      - name: availability
        in: query
        description: motor current availability
        type: string
        enum:
        - regular
        - occasional
        - OOP
        - available
        - all
        required: false
      responses:
        '200':
          description: metadata response
          schema:
            $ref: '#/definitions/MetadataResponse'
    post:
      tags:
      - metadata
      description: The POST method specifies JSON object with search criteria.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: metadata query criteria
        required: true
        schema:
          $ref: '#/definitions/MetadataRequest'
      responses:
        '200':
          description: metadata response
          schema:
            $ref: '#/definitions/MetadataResponse'

  /search.json:
    post:
      tags:
      - search
      description: The POST method specifies a JSON object with search criteria.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: metadata query criteria
        required: true
        schema:
          $ref: '#/definitions/MetadataRequest'
      responses:
        '200':
          description: metadata response
          schema:
            $ref: '#/definitions/MetadataResponse'

paths:
  /download.json:
    post:
      tags:
      - search
      description: POST method specifies JSON object with criteria

definitions:
  MetadataRequest:
    type: object
    description: metadata query criteria
    properties:
      manufacturer:
        description: manufacturer name or abbreviation
        type: string
        example: Estes
      impulseClass:
        description: letter class of motor
        type: string
        example: C
      diameter:
        description: motor diameter in mm
        type: number
        example: 18
      type:
        description: motor type
        type: string
        enum:
        - SU
        - reload
        - hybrid
        example: SU
      certOrg:
        description: certification organization name or abbreviation
        type: string
        example: NAR
      availability:
        description: motor current availability
        type: string
        enum:
        - regular
        - occasional
        - OOP
        - available
        - all
        example: available

  MetadataResponse:
    type: object
    description: motor metadata
    properties:
      manufacturers:
        type: array
        description: motor manufacturers
        items:
          $ref: '#/definitions/NameAndAbbrev'
        example:
        - name: Estes Industries
          abbrev: Estes
      certOrgs:
        type: array
        description: certification organizations
        items:
          $ref: '#/definitions/NameAndAbbrev'
        example:
        - name: National Association of Rocketry
          abbrev: NAR
      types:
        type: array
        description: motor types
        items:
          type: string
          enum:
          - SU
          - reload
          - hybrid
        example:
        - SU
      diameters:
        type: array
        description: motor diameters
        items:
          type: number
        example:
        - 13
        - 18
      impulseClasses:
        type: array
        description: total impulse letter classes
        items:
          type: string
        example:
        - A
        - B
        - C

  NameAndAbbrev:
    type: object
    description: full name and abbreviation
    properties:
      name:
        type: string
        description: full (official) name
      abbrev:
        type: string
        description: most common abbreviation
